import uuid
from rest_framework import serializers
from .models import Library


class LibrarySerializer(serializers.ModelSerializer):
    """
    Serializer for the Library model.

    A ModelSerializer automatically generates serializer fields based on
    the model's fields, which saves us from redeclaring name/url/etc by
    hand. We still need to override behaviour for a couple of fields
    (library_id, created_at) and the create() method, explained below.
    """

    class Meta:
        # Tells the serializer which model to base itself on.
        model = Library

        # Explicitly list every field we want exposed through the API.
        # Being explicit (rather than using '__all__') is good practice —
        # it means if we add a sensitive field to the model later, it
        # won't accidentally get exposed through the API until we
        # deliberately add it here.
        fields = [
            "library_id",
            "name",
            "logo",
            "url",
            "primary_color",
            "secondary_color",
            "enabled_modules",
            "status",
            "created_at",
        ]

        # read_only_fields means: these fields will be INCLUDED when we
        # serialize a Library OUT to JSON (e.g. in the response after
        # creation), but the client is NOT allowed to set them when
        # sending data IN. This matches the database design:
        #   - library_id is normally generated by Postgres
        #     (gen_random_uuid()), not chosen by the client.
        #   - created_at is set automatically by Django (auto_now_add)
        #     at the moment the row is created.
        read_only_fields = [
            "library_id",
            "created_at",
        ]

    def create(self, validated_data):
        """
        Overrides the default ModelSerializer.create() behaviour.

        Why we need this: our Library model has `managed = False`, which
        means Django never generated this table itself, so it has no
        knowledge of the table's DEFAULT gen_random_uuid() at the database
        level. Normally, leaving library_id out entirely and just calling
        Library.objects.create(**validated_data) would send an INSERT
        without a value for library_id, and rely on Postgres to fill it
        in via its DEFAULT clause — but Django's ORM doesn't handle that
        gap automatically for fields it doesn't manage.

        To keep things simple and reliable, we generate the UUID on the
        Python/Django side instead, using the same uuid4 algorithm
        Postgres's gen_random_uuid() effectively uses. This guarantees
        every Library created through the API always gets a valid,
        unique library_id without depending on database-side defaults
        being triggered correctly through the ORM.
        """
        validated_data["library_id"] = uuid.uuid4()
        return Library.objects.create(**validated_data)

    def update(self, instance, validated_data):
        """
        Overrides the default ModelSerializer.update() behaviour.

        `instance` is the existing Library object fetched from the
        database by the view (the one we're updating). `validated_data`
        is the cleaned, validated data sent in the PUT or PATCH request
        body — it will never contain library_id or created_at because
        those are declared as read_only_fields above, so DRF strips them
        out before validation even runs.

        How PUT vs PATCH works here:
        - PUT: the client sends ALL editable fields. validated_data will
          contain every field (name, logo, url, primary_color,
          secondary_color, enabled_modules). Any field the client omits
          will fail validation since fields are required by default.
        - PATCH: the client sends ONLY the fields they want to change.
          validated_data will only contain those fields. Fields not
          included are left untouched on the instance, because we use
          validated_data.get(field, current_value) below.

        The view controls which method is used — our UpdateAPIView
        supports both PUT and PATCH automatically.
        """
        # For each editable field, update the instance's attribute with
        # the new value if it was provided, or keep the existing value
        # if it wasn't (this is what makes PATCH work correctly).
        instance.name = validated_data.get("name", instance.name)
        instance.logo = validated_data.get("logo", instance.logo)
        instance.url = validated_data.get("url", instance.url)
        instance.primary_color = validated_data.get(
            "primary_color", instance.primary_color
        )
        instance.secondary_color = validated_data.get(
            "secondary_color", instance.secondary_color
        )
        instance.enabled_modules = validated_data.get(
            "enabled_modules", instance.enabled_modules
        )

        # Persist the changes to the database. Django's ORM generates an
        # UPDATE SQL statement targeting the row with this instance's
        # primary key (library_id).
        instance.save()

        # Return the updated instance so DRF can serialize it back to
        # JSON for the response.
        return instance

    def validate_name(self, value):
        """
        Field-level validation for `name`.

        DRF automatically calls a method named `validate_<field_name>`
        if it exists, passing in just that field's value. This runs in
        addition to the automatic checks DRF already does because of
        the model (e.g. uniqueness, max_length).

        Here we strip whitespace and reject empty/whitespace-only names,
        since the database only enforces NOT NULL, not "not just spaces".
        """
        cleaned_value = value.strip()
        if not cleaned_value:
            raise serializers.ValidationError(
                "Library name cannot be empty or just whitespace."
            )
        return cleaned_value

    def validate_status(self, value):
        """
        Validates that status is one of the allowed values defined in
        Library.Status. Although DRF already enforces choices validation
        automatically when choices are set on the model field, we add
        this explicit validator to return a clear, descriptive error
        message rather than the default generic one — making the API
        easier to consume for front-end developers.
        """
        allowed = [choice[0] for choice in Library.Status.choices]
        if value not in allowed:
            raise serializers.ValidationError(
                f"Invalid status '{value}'. Must be one of: {', '.join(allowed)}."
            )
        return value

    def validate_enabled_modules(self, value):
        """
        Ensures enabled_modules, if provided, is actually a JSON object
        (Python dict) rather than a list, string, or number. The database
        column is JSONB, which technically allows any valid JSON value,
        but for our use case ("which modules are enabled") we want to
        enforce that it's always a key-value mapping like:
            {"members": true, "fines": false}
        """
        if value is not None and not isinstance(value, dict):
            raise serializers.ValidationError(
                'enabled_modules must be a JSON object (e.g. {"members": true}).'
            )
        return value
