services:
  db:
    image: postgres:16
    container_name: library_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-library_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
    ports:
       - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-library_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
      image: redis:7
      container_name: redis_library_broker
      restart: unless-stopped
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
