# Generated by Django 6.0.5 on 2026-09-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationlog',
            name='uniq_notification_per_transaction_type_date',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='reservation_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='borrow_transaction_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('due_soon', 'Due Soon'), ('overdue', 'Overdue'), ('reservation_reminder', 'Reservation Reminder')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['reservation_id', 'notification_type', 'sent_for_date'], name='idx_notif_reservation_dedup'),
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(condition=models.Q(('borrow_transaction_id__isnull', False)), fields=('borrow_transaction_id', 'notification_type', 'sent_for_date'), name='uniq_notification_per_transaction_type_date'),
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(condition=models.Q(('reservation_id__isnull', False)), fields=('reservation_id', 'notification_type', 'sent_for_date'), name='uniq_notification_per_reservation_type_date'),
        ),
    ]
