"""
serializers.py — BookCopySerializer
=====================================

A "serializer" in Django REST Framework (DRF) does two jobs:

  1. SERIALIZATION: takes a Python object (a BookCopy model instance)
     and converts it into something that can be turned into JSON to
     send back to the client (a browser, a mobile app, etc).

  2. DESERIALIZATION / VALIDATION: takes incoming JSON (e.g. from a
     POST request) and converts + validates it back into Python data
     that can be used to create/update a model instance.

For this module we only need read (list) functionality, but we're
using ModelSerializer here rather than a plain Serializer because it
also gives us validation "for free" if we build create/update views
later — no extra cost now, and it saves rewriting this file later.
"""

from rest_framework import serializers

from .models import BookCopy


class BookCopySerializer(serializers.ModelSerializer):
    """
    Converts BookCopy model instances <-> JSON.

    ModelSerializer automatically:
      - Inspects the `model` given in Meta.
      - Generates a serializer field for each model field listed in
        Meta.fields (matching type, e.g. UUIDField -> UUIDField,
        CharField -> CharField, DateTimeField -> DateTimeField).
      - Applies the same constraints your model already has
        (e.g. `unique=True` on barcode, `choices=` on status/condition).

    This means we don't have to manually redeclare every field type —
    DRF reads that information straight from the BookCopy model.
    """

    # `source='library.name'` reaches through the `library` foreign key
    # to pull the related Library's `name` field, and exposes it as a
    # flat, read-only `library_name` field in the JSON output. This is
    # purely for convenience so API consumers don't have to make a
    # second request just to know which library a copy belongs to.
    #
    # `read_only=True` means this field is only used when OUTPUTTING
    # data (serialization) — it's ignored if someone tries to POST/PUT
    # a value for it, since it's not really a field you set directly;
    # you'd set `library` (the FK id) instead.
    library_name = serializers.CharField(source='library.name', read_only=True)

    # Same idea, but reaching through the `book` foreign key to expose
    # the related Book's title alongside the raw book_id.
    book_title = serializers.CharField(source='book.title', read_only=True)

    class Meta:
        # Tells DRF which model this serializer is based on.
        model = BookCopy

        # Explicit whitelist of fields to include in the JSON output.
        # Being explicit (rather than using fields = '__all__') is
        # good practice: it makes it obvious at a glance exactly what
        # the API exposes, and prevents accidentally leaking a field
        # later if the model gains new columns.
        fields = [
            'id',
            'library',        # raw FK — will serialize as the library's UUID
            'library_name',   # convenience field, see above
            'book',            # raw FK — will serialize as the book's UUID
            'book_title',      # convenience field, see above
            'barcode',
            'status',
            'condition',
            'shelf_location',
            'acquired_at',
            'created_at',
        ]

        # Fields the client should never be able to set/overwrite via
        # the API, even if they're included in `fields` above. `id` and
        # `created_at` are generated by the system, not supplied by
        # a user — this matters once we add create/update endpoints.
        read_only_fields = ['id', 'created_at']

class BookCopyBulkUpdateItemSerializer(serializers.Serializer):
    """
    Validates ONE entry within a bulk-update request body.

    Unlike BookCopySerializer (a ModelSerializer, which exposes the
    whole model), this is a plain `serializers.Serializer` — we're
    deliberately hand-picking a much narrower set of fields here,
    because bulk updates are only allowed to touch:
        status, condition, shelf_location, acquired_at

    Notably ABSENT on purpose: barcode, library, book. Those identify
    WHICH physical item a copy is and which library/book it belongs
    to — a bulk "update details" action has no business changing them,
    so they're simply never declared here. Even if a client includes
    them in the request JSON, DRF silently ignores any field that
    isn't declared on the serializer, so there's no risk of them
    sneaking through.

    A single bulk-update request body will contain a LIST of these,
    e.g.:
        [
            {"id": "<uuid>", "status": "borrowed"},
            {"id": "<uuid>", "condition": "good", "shelf_location": "B2-04"}
        ]
    """

    # `id` identifies WHICH BookCopy row this particular update applies
    # to. It's required — without it we wouldn't know what to update —
    # but note this is only used to look the row up; it's not itself
    # one of the "updatable" columns.
    id = serializers.UUIDField(required=True)

    # Every actual column below is `required=False`, because a client
    # updating a batch of copies might change different fields on
    # different rows in the SAME request (e.g. row A only needs a new
    # status, row B only needs a new shelf_location). We validate in
    # `validate()` below that AT LEAST ONE of them was actually
    # provided, so "just an id and nothing else" is rejected as
    # pointless rather than silently accepted.
    status = serializers.ChoiceField(choices=BookCopy.STATUS_CHOICES, required=False)
    condition = serializers.ChoiceField(choices=BookCopy.CONDITION_CHOICES, required=False)

    # `allow_null=True` permits explicitly clearing shelf_location by
    # sending `"shelf_location": null` (the underlying DB column and
    # model field both allow NULL — see models.py).
    shelf_location = serializers.CharField(
        max_length=100, required=False, allow_null=True, allow_blank=True
    )
    acquired_at = serializers.DateTimeField(required=False, allow_null=True)

    def validate(self, attrs):
        """
        `validate()` runs AFTER each individual field has already
        passed its own validation (e.g. status is a real choice,
        acquired_at is a real datetime). This is the right place for
        validation that involves MULTIPLE fields together, rather than
        any single field in isolation.

        Here we make sure the client sent at least one column to
        actually update, besides the `id` used to find the row.
        """
        updatable_fields = {'status', 'condition', 'shelf_location', 'acquired_at'}
        if not updatable_fields.intersection(attrs.keys()):
            raise serializers.ValidationError(
                'At least one of status, condition, shelf_location or '
                'acquired_at must be provided for each item.'
            )
        return attrs