"""
serializers.py — BookCopySerializer
=====================================

A "serializer" in Django REST Framework (DRF) does two jobs:

  1. SERIALIZATION: takes a Python object (a BookCopy model instance)
     and converts it into something that can be turned into JSON to
     send back to the client (a browser, a mobile app, etc).

  2. DESERIALIZATION / VALIDATION: takes incoming JSON (e.g. from a
     POST request) and converts + validates it back into Python data
     that can be used to create/update a model instance.

For this module we only need read (list) functionality, but we're
using ModelSerializer here rather than a plain Serializer because it
also gives us validation "for free" if we build create/update views
later — no extra cost now, and it saves rewriting this file later.
"""

from rest_framework import serializers

from .models import BookCopy


class BookCopySerializer(serializers.ModelSerializer):
    """
    Converts BookCopy model instances <-> JSON.

    ModelSerializer automatically:
      - Inspects the `model` given in Meta.
      - Generates a serializer field for each model field listed in
        Meta.fields (matching type, e.g. UUIDField -> UUIDField,
        CharField -> CharField, DateTimeField -> DateTimeField).
      - Applies the same constraints your model already has
        (e.g. `unique=True` on barcode, `choices=` on status/condition).

    This means we don't have to manually redeclare every field type —
    DRF reads that information straight from the BookCopy model.
    """

    # `source='library.name'` reaches through the `library` foreign key
    # to pull the related Library's `name` field, and exposes it as a
    # flat, read-only `library_name` field in the JSON output. This is
    # purely for convenience so API consumers don't have to make a
    # second request just to know which library a copy belongs to.
    #
    # `read_only=True` means this field is only used when OUTPUTTING
    # data (serialization) — it's ignored if someone tries to POST/PUT
    # a value for it, since it's not really a field you set directly;
    # you'd set `library` (the FK id) instead.
    library_name = serializers.CharField(source='library.name', read_only=True)

    # Same idea, but reaching through the `book` foreign key to expose
    # the related Book's title alongside the raw book_id.
    book_title = serializers.CharField(source='book.title', read_only=True)

    class Meta:
        # Tells DRF which model this serializer is based on.
        model = BookCopy

        # Explicit whitelist of fields to include in the JSON output.
        # Being explicit (rather than using fields = '__all__') is
        # good practice: it makes it obvious at a glance exactly what
        # the API exposes, and prevents accidentally leaking a field
        # later if the model gains new columns.
        fields = [
            'id',
            'library',        # raw FK — will serialize as the library's UUID
            'library_name',   # convenience field, see above
            'book',            # raw FK — will serialize as the book's UUID
            'book_title',      # convenience field, see above
            'barcode',
            'status',
            'condition',
            'shelf_location',
            'acquired_at',
            'created_at',
        ]

        # Fields the client should never be able to set/overwrite via
        # the API, even if they're included in `fields` above. `id` and
        # `created_at` are generated by the system, not supplied by
        # a user — this matters once we add create/update endpoints.
        read_only_fields = ['id', 'created_at']