from django.contrib import admin
from .models import Member


# Registering a model with Django admin gives you a fully working CRUD
# (Create, Read, Update, Delete) interface for it at /admin/, without
# having to write any HTML or views yourself. This is extremely useful
# while developing — it lets us create/inspect Member rows through a
# browser UI before the API endpoints even exist.
#
# We use the @admin.register decorator here instead of calling
# admin.site.register(Member, MemberAdmin) separately — both do the
# same thing, but the decorator form is the more modern/common style.
@admin.register(Member)
class MemberAdmin(admin.ModelAdmin):
    """
    Customises how the Member model is displayed and managed inside the
    Django admin site. By default, admin would just show every field in a
    plain form and list view — here we tailor that a bit for usability.
    """

    # Controls which columns are shown in the admin's list page (the page
    # listing all Member rows). Without this, admin would only show the
    # result of __str__() (i.e. just the name) for each row.
    list_display = (
        "member_id",
        "library",
        "membership_no",
        "name",
        "email",
        "phone_number",
        "address",
        "status",
        "gender",
        "membership_type",
        "created_at",
    )

    # Adds a search box to the admin list page, letting staff search
    # Member rows . Django translates this into a SQL
    # LIKE/ILIKE query under the hood.
    search_fields = (
        "name", "membership_no", "email", "phone_number"
    )

    # Adds filter options in the sidebar of the list page. Since
    # created_at is a date field, Django automatically gives a handy
    # "Today / Past 7 days / This month / This year" filter for it.
    list_filter = ("created_at",)

    # Fields that should be visible on the detail/edit page but not
    # directly editable by hand — these are either auto-generated by the
    # database (member_id) or auto-set by Django (created_at).
    readonly_fields = (
        "member_id",
        "created_at",
    )

    # Default ordering for the list page — newest libraries first.
    ordering = ("-created_at",)
