from django.contrib import admin
from .models import Library


# Registering a model with Django admin gives you a fully working CRUD
# (Create, Read, Update, Delete) interface for it at /admin/, without
# having to write any HTML or views yourself. This is extremely useful
# while developing — it lets us create/inspect Library rows through a
# browser UI before the API endpoints even exist.
#
# We use the @admin.register decorator here instead of calling
# admin.site.register(Library, LibraryAdmin) separately — both do the
# same thing, but the decorator form is the more modern/common style.
@admin.register(Library)
class LibraryAdmin(admin.ModelAdmin):
    """
    Customises how the Library model is displayed and managed inside the
    Django admin site. By default, admin would just show every field in a
    plain form and list view — here we tailor that a bit for usability.
    """

    # Controls which columns are shown in the admin's list page (the page
    # listing all Library rows). Without this, admin would only show the
    # result of __str__() (i.e. just the name) for each row.
    list_display = (
        "name",
        "logo",
        "url",
        "primary_color",
        "secondary_color",
        "enabled_modules",
        "created_at",
    )

    # Adds a search box to the admin list page, letting staff search
    # Library rows by name or url. Django translates this into a SQL
    # LIKE/ILIKE query under the hood.
    search_fields = (
        "name",
        "url",
    )

    # Adds filter options in the sidebar of the list page. Since
    # created_at is a date field, Django automatically gives a handy
    # "Today / Past 7 days / This month / This year" filter for it.
    list_filter = ("created_at",)

    # Fields that should be visible on the detail/edit page but not
    # directly editable by hand — these are either auto-generated by the
    # database (library_id) or auto-set by Django (created_at).
    readonly_fields = (
        "library_id",
        "created_at",
    )

    # Controls the order and grouping of fields on the add/edit form.
    # Using fieldsets (instead of plain `fields`) lets us add section
    # headings, which makes the form easier to read as more fields/
    # modules get added later.
    fieldsets = (
        (
            "Identification",
            {
                "fields": ("library_id", "name", "url"),
            },
        ),
        (
            "Branding",
            {
                "fields": ("logo", "primary_color", "secondary_color"),
            },
        ),
        (
            "Configuration",
            {
                "fields": ("enabled_modules",),
            },
        ),
        (
            "Metadata",
            {
                "fields": ("created_at",),
            },
        ),
    )

    # Default ordering for the list page — newest libraries first.
    ordering = ("-created_at",)
