# Generated by Django 6.0.5 on 2026-09-14 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_copies', models.IntegerField(db_column='total_copies')),
                ('available_copies', models.IntegerField(db_column='available_copies')),
                ('borrowed_copies', models.IntegerField(db_column='borrowed_copies')),
                ('reserved_copies', models.IntegerField(db_column='reserved_copies')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'db_table': 'inventory',
                'managed': False,
            },
        ),
    ]
