# Generated by Django 6.0.5 on 2026-09-07 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.UUIDField(db_column='member_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membership_no', models.CharField(db_column='membership_no', max_length=50, unique=True)),
                ('name', models.CharField(db_column='name', max_length=120)),
                ('email', models.CharField(db_column='email', max_length=255)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=20)),
                ('address', models.CharField(blank=True, db_column='address', max_length=255, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], db_column='gender', default='female', max_length=10)),
                ('membership_type', models.CharField(choices=[('student', 'Student'), ('normal', 'Normal')], db_column='membership_type', default='normal', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_column='status', default='inactive', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'members',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='activation_tokens', to='members.member')),
            ],
            options={
                'verbose_name': 'Member Activation Token',
                'verbose_name_plural': 'Member Activation Tokens',
                'db_table': 'member_activation_tokens',
            },
        ),
    ]