# Generated by Django 6.0.5 on 2026-08-21 00:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrow_transaction_id', models.UUIDField(db_index=True)),
                ('notification_type', models.CharField(choices=[('due_soon', 'Due Soon'), ('overdue', 'Overdue')], max_length=20)),
                ('sent_for_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification Log Entry',
                'verbose_name_plural': 'Notification Log Entries',
                'db_table': 'notification_log',
                'indexes': [models.Index(fields=['borrow_transaction_id', 'notification_type', 'sent_for_date'], name='idx_notification_dedup_lookup')],
                'constraints': [models.UniqueConstraint(fields=('borrow_transaction_id', 'notification_type', 'sent_for_date'), name='uniq_notification_per_transaction_type_date')],
            },
        ),
    ]
